# Generated by Django 5.2.6 on 2025-10-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(blank=True, choices=[('haircut', 'haircut'), ('hair_beard', 'hair_beard')], max_length=20),
        ),
    ]
