# Generated by Django 5.2.6 on 2025-11-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_appointment_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='FollowUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(blank=True, help_text='Preferred language (de/en)', max_length=5, null=True)),
                ('opt_out', models.BooleanField(default=False, help_text='Customer opted out of follow-up emails')),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_requests', to='bookings.appointment')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['email'], name='bookings_fo_email_9bb168_idx'), models.Index(fields=['opt_out'], name='bookings_fo_opt_out_875dbd_idx')],
            },
        ),
    ]
