# Generated by Django 5.2.6 on 2025-11-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_followuprequest_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followuprequest',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Follow-up Request', 'verbose_name_plural': 'Follow-up Requests'},
        ),
        migrations.RemoveField(
            model_name='followuprequest',
            name='email',
        ),
        migrations.AddField(
            model_name='followuprequest',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='followuprequest',
            name='bounce_type',
            field=models.CharField(blank=True, help_text='Bounce type (hard/soft)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='followuprequest',
            name='complaint',
            field=models.BooleanField(default=False, help_text='Spam complaint received'),
        ),
        migrations.AddField(
            model_name='followuprequest',
            name='opted_out_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of opt-out action', null=True),
        ),
        migrations.AddField(
            model_name='followuprequest',
            name='webhook_event_data',
            field=models.JSONField(blank=True, help_text='Raw webhook event data', null=True),
        ),
        migrations.AlterField(
            model_name='followuprequest',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_request', to='bookings.appointment', unique=True),
        ),
        migrations.AddIndex(
            model_name='followuprequest',
            index=models.Index(fields=['sent_at'], name='bookings_fo_sent_at_abc123_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='followup_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='followup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
