# Generated by Django 5.0.7 on 2025-09-29 23:27

import barbers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=barbers.models.barber_photo_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
