# Generated by Django 5.2.6 on 2025-10-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='working_days',
            field=models.CharField(default='0,1,2,3,4,5', help_text='Comma separated weekday numbers (0=Mon ... 6=Sun).', max_length=20),
        ),
    ]
