name: CI Backend
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django check
        working-directory: backend
        env:
          DJANGO_SETTINGS_MODULE: config.settings
        run: |
          python manage.py check