name: Deploy to Hetzner

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deployment-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SERVER_IP }}
      SSH_USER: ${{ secrets.SERVER_USER }}
      SSH_PASS: ${{ secrets.SERVER_PASS }}
      SSH_PORT: ${{ secrets.SERVER_PORT }}
      REPO_URL: https://github.com/${{ github.repository }}.git
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Copy remote deploy script
        run: |
          set -euo pipefail
          install -m 0755 deploy/remote.sh /tmp/remote.sh
          sshpass -p "${SSH_PASS}" scp -P "${SSH_PORT}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/remote.sh "${SSH_USER}@${SSH_HOST}:/tmp/remote.sh"

      - name: Execute remote deploy
        run: |
          set -euo pipefail
          sshpass -p "${SSH_PASS}" ssh -p "${SSH_PORT}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${SSH_USER}@${SSH_HOST}" \
            "APP_DIR='/srv/meister' REPO_URL='${REPO_URL}' bash /tmp/remote.sh"
