name: Deploy to Hetzner

on:
  push:
    branches:
      - main

concurrency:
  group: deployment-main
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SERVER_IP }}
      SSH_USER: ${{ secrets.SERVER_USER }}
      SSH_PASS: ${{ secrets.SERVER_PASS }}
      SSH_PORT: ${{ secrets.SERVER_PORT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images (verification)
        run: |
          docker compose build --progress=plain

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Hetzner host
        run: |
          set -euo pipefail
          sshpass -p "${SSH_PASS}" ssh -o StrictHostKeyChecking=no -p "${SSH_PORT}" "${SSH_USER}@${SSH_HOST}" '
            set -euo pipefail
            cd /root/Meister-Barbershop
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            sleep 15
            docker compose ps
            docker ps
            STATUS=$(curl -s -o /tmp/deploy_curl.log -w "%{http_code}" http://localhost || true)
            if [ "${STATUS}" -lt 200 ] || [ "${STATUS}" -ge 300 ]; then
              echo "Unexpected HTTP status: ${STATUS}"
              cat /tmp/deploy_curl.log || true
              exit 1
            fi
            echo "Application responded with HTTP ${STATUS}"
          '
